analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - prefer_const_constructors
    - public_member_api_docs
    - always_use_package_imports
    # … add other rules you want
