name: responsive_scaler
description: A Flutter package that offers automatic, boilerplate-free responsive scaling for text, icons, and spacing across different screen sizes.
version: 0.0.2
homepage: https://github.com/Mudit200408/
repository: https://github.com/Mudit200408/responsive_scaler
issue_tracker: https://github.com/Mudit200408/responsive_scaler/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

topics:
  - responsive
  - ui
  - scaling
  - text
  - material-design

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Flutter section is not needed for packages unless you have assets